# Exploration du projet Tableau de bord Pompiers

Ce notebook présente les étapes de réflexion du projet.

L'objectif est de comprendre les données, de les nettoyer, puis de préparer les analyses utilisées dans le tableau de bord Excel.

## 1. Import des bibliothèques

On commence par importer pandas. Cette bibliothèque permet de lire et manipuler les données sous forme de tableau.

In [1]:
import pandas as pd

## 2. Chargement des données

Le fichier utilisé est `interventions2023.csv`.

Il contient les interventions des services de secours en 2023.

In [2]:
df = pd.read_csv(
    "../data/interventions2023.csv",
    sep=";",
    encoding="utf-8"
)

df.head()

,Ann�e,Zone,R�gion,Num�ro,D�partement,Cat�gorie A,Feux d'habitations-bureaux,dont feux de chemin�es,Feux d'ERP avec local � sommeil,Feux d'ERP sans local � sommeil,...,D�gagements de voies publiques,Nettoyages de voies publiques,�boulements,D�poses d'objets,Piquets de s�curit� - surveillances,Engins explosifs,Autres op�rations diverses,Divers,Op�rations diverses,Total interventions
0,2023,Sud,Provence-Alpes-C�te d'Azur,BMPM,Bouches-du-Rh�ne,NaN,774,9,35,176,...,577,137,12,0,1 867,0,724,8 356,12 167,120 317
1,2023,�le-de-France,�le-de-France,BSPP,Paris,NaN,3 763,37,118,650,...,36,234,41,994,0,17,14 344,18 371,19 365,495 397
2,2023,Sud-est,Auvergne-Rh�ne-Alpes,1,Ain,B,507,198,22,19,...,140,16,29,114,3,3,1 026,6 152,7 024,43 391
3,2023,Nord,Hauts-de-France,2,Aisne,B,931,316,24,56,...,92,0,3,198,0,1,346,3 022,4 467,36 090
4,2023,Sud-est,Auvergne-Rh�ne-Alpes,3,Allier,C,450,0,11,19,...,184,15,1,142,26,0,805,1 364,1 813,29 538

## 3. Première observation du jeu de données

On regarde la taille du jeu de données et les colonnes disponibles.

In [3]:
df.shape

(99, 71)

In [4]:
df.columns

Index(['Ann�e', 'Zone', 'R�gion', 'Num�ro', 'D�partement', 'Cat�gorie A',
       'Feux d'habitations-bureaux', 'dont feux de chemin�es',
       'Feux d'ERP avec local � sommeil', 'Feux d'ERP sans local � sommeil',
       'Feux de locaux industriels', 'Feux de locaux artisanaux',
       'Feux de locaux agricoles', 'Feux sur voie publique',
       'Feux de v�hicules', 'Feux de v�g�tations', 'Autres feux', 'Incendies',
       'Accidents sur lieux de travail', 'Accidents � domicile',
       'Accidents de sport', 'Accidents sur voie publique',
       'Secours en montagne', 'Malaises sur lieux de travail',
       'Malaises � domicile : urgence vitale', 'Malaises � domicile : carence',
       'Malaises en sport', 'Malaises sur voie publique', 'Autolyses',
       'Secours en piscines ou eaux int�rieures', 'Secours en mer (FDSM)',
       'Intoxications', 'dont intoxications au CO', 'Autres SAV',
       'Secours � victime', 'Relevage de personnes', 'Recherche de personnes',
       'Aides � personne', 'Secours � personne', 'Accidents routiers',
       'Accidents ferroviaires', 'Accidents a�riens',
       'Accidents de navigation', 'Accidents de t�l�portage',
       'Accidents de circulation', 'Odeurs - fuites de gaz',
       'Odeurs (autres que gaz)', 'Fait dus � l'�lectricit�',
       'Pollutions - contaminations', 'Autres risques technologiques',
       'Risques technologiques', 'Fuites d'eau', 'Inondations',
       'Ouvertures de portes', 'Recherches d'objets', 'Bruits suspects',
       'Protection des biens', 'Fausses alertes', 'dont fausses alertes DAAF',
       'Faits d'animaux (hors hym�nopt�res)', 'Hym�nopt�res',
       'D�gagements de voies publiques', 'Nettoyages de voies publiques',
       '�boulements', 'D�poses d'objets',
       'Piquets de s�curit� - surveillances', 'Engins explosifs',
       'Autres op�rations diverses', 'Divers', 'Op�rations diverses',
       'Total interventions'],
      dtype='object')

Le jeu de données contient 99 lignes et 71 colonnes.

Les colonnes principales sont :
- la zone ;
- la région ;
- le département ;
- les types d'interventions ;
- le total des interventions.

## 4. Vérification des types de données

Cette étape permet de vérifier si les colonnes numériques sont bien reconnues comme des nombres.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 71 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Ann�e                                    99 non-null     int64
 1   Zone                                     99 non-null     object
 2   R�gion                                   99 non-null     object
 3   Num�ro                                   99 non-null     object
 4   D�partement                              99 non-null     object
 5   Cat�gorie A                              97 non-null     object
 6   Feux d'habitations-bureaux               99 non-null     object
 7   dont feux de chemin�es                   99 non-null     int64
 8   Feux d'ERP avec local � sommeil          99 non-null     int64
 9   Feux d'ERP sans local � sommeil          99 non-null     int64
 10  Feux de locaux industriels               99 non-null     int64
 11  Feux de locaux artisanaux                99 non-null     int64
 12  Feux de locaux agricoles                 99 non-null     int64
 13  Feux sur voie publique                   99 non-null     object
 14  Feux de v�hicules                        99 non-null     object
 15  Feux de v�g�tations                      99 non-null     object
 16  Autres feux                              99 non-null     object
 17  Incendies                                99 non-null     object
 18  Accidents sur lieux de travail           99 non-null     object
 19  Accidents � domicile                     99 non-null     object
 20  Accidents de sport                       99 non-null     object
 21  Accidents sur voie publique              99 non-null     object
 22  Secours en montagne                      99 non-null     int64
 23  Malaises sur lieux de travail            99 non-null     object
 24  Malaises � domicile : urgence vitale     99 non-null     object
 25  Malaises � domicile : carence            99 non-null     object
 26  Malaises en sport                        99 non-null     object
 27  Malaises sur voie publique               99 non-null     object
 28  Autolyses                                99 non-null     object
 29  Secours en piscines ou eaux int�rieures  99 non-null     int64
 30  Secours en mer (FDSM)                    99 non-null     int64
 31  Intoxications                            99 non-null     object
 32  dont intoxications au CO                 99 non-null     int64
 33  Autres SAV                               99 non-null     object
 34  Secours � victime                        99 non-null     object
 35  Relevage de personnes                    99 non-null     object
 36  Recherche de personnes                   99 non-null     object
 37  Aides � personne                         99 non-null     object
 38  Secours � personne                       99 non-null     object
 39  Accidents routiers                       99 non-null     object
 40  Accidents ferroviaires                   99 non-null     int64
 41  Accidents a�riens                        99 non-null     int64
 42  Accidents de navigation                  99 non-null     int64
 43  Accidents de t�l�portage                 99 non-null     int64
 44  Accidents de circulation                 99 non-null     object
 45  Odeurs - fuites de gaz                   99 non-null     object
 46  Odeurs (autres que gaz)                  99 non-null     object
 47  Fait dus � l'�lectricit�                 99 non-null     int64
 48  Pollutions - contaminations              99 non-null     int64
 49  Autres risques technologiques            99 non-null     int64
 50  Risques technologiques                   99 non-null     object
 51  Fuites d'eau                             99 non-null     object
 52  Inondations                              99 non-null     object
 53  Ouvertures de portes                     99 non-null     object
 54  Recherches d'objets                      99 non-null     object
 55  Bruits suspects                          99 non-null     object
 56  Protection des biens                     99 non-null     object
 57  Fausses alertes                          99 non-null     object
 58  dont fausses alertes DAAF                99 non-null     int64
 59  Faits d'animaux (hors hym�nopt�res)      99 non-null     object
 60  Hym�nopt�res                             99 non-null     object
 61  D�gagements de voies publiques           99 non-null     object
 62  Nettoyages de voies publiques            99 non-null     int64
 63  �boulements                              99 non-null     int64
 64  D�poses d'objets                         99 non-null     object
 65  Piquets de s�curit� - surveillances      99 non-null     object
 66  Engins explosifs                         99 non-null     int64
 67  Autres op�rations diverses               99 non-null     object
 68  Divers                                   99 non-null     object
 69  Op�rations diverses                      99 non-null     object
 70  Total interventions                      99 non-null     object
dtypes: int64(22), object(49)
memory usage: 55.0+ KB

On observe que certaines colonnes qui devraient être numériques sont lues comme du texte.

Cela vient du format du fichier CSV. Certains nombres contiennent des espaces, par exemple `12 345`.

Il faut donc nettoyer ces colonnes avant de faire des calculs.

## 5. Nettoyage des noms de colonnes

Pour faciliter le code, on met les noms de colonnes en minuscules et on remplace les espaces par des underscores.

In [6]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.columns

Index(['ann�e', 'zone', 'r�gion', 'num�ro', 'd�partement', 'cat�gorie_a',
       'feux_d'habitations-bureaux', 'dont_feux_de_chemin�es',
       'feux_d'erp_avec_local_�_sommeil', 'feux_d'erp_sans_local_�_sommeil',
       'feux_de_locaux_industriels', 'feux_de_locaux_artisanaux',
       'feux_de_locaux_agricoles', 'feux_sur_voie_publique',
       'feux_de_v�hicules', 'feux_de_v�g�tations', 'autres_feux', 'incendies',
       'accidents_sur_lieux_de_travail', 'accidents_�_domicile',
       'accidents_de_sport', 'accidents_sur_voie_publique',
       'secours_en_montagne', 'malaises_sur_lieux_de_travail',
       'malaises_�_domicile_:_urgence_vitale', 'malaises_�_domicile_:_carence',
       'malaises_en_sport', 'malaises_sur_voie_publique', 'autolyses',
       'secours_en_piscines_ou_eaux_int�rieures', 'secours_en_mer_(fdsm)',
       'intoxications', 'dont_intoxications_au_co', 'autres_sav',
       'secours_�_victime', 'relevage_de_personnes', 'recherche_de_personnes',
       'aides_�_personne', 'secours_�_personne', 'accidents_routiers',
       'accidents_ferroviaires', 'accidents_a�riens',
       'accidents_de_navigation', 'accidents_de_t�l�portage',
       'accidents_de_circulation', 'odeurs_-_fuites_de_gaz',
       'odeurs_(autres_que_gaz)', 'fait_dus_�_l'�lectricit�',
       'pollutions_-_contaminations', 'autres_risques_technologiques',
       'risques_technologiques', 'fuites_d'eau', 'inondations',
       'ouvertures_de_portes', 'recherches_d'objets', 'bruits_suspects',
       'protection_des_biens', 'fausses_alertes', 'dont_fausses_alertes_daaf',
       'faits_d'animaux_(hors_hym�nopt�res)', 'hym�nopt�res',
       'd�gagements_de_voies_publiques', 'nettoyages_de_voies_publiques',
       '�boulements', 'd�poses_d'objets',
       'piquets_de_s�curit�_-_surveillances', 'engins_explosifs',
       'autres_op�rations_diverses', 'divers', 'op�rations_diverses',
       'total_interventions'],
      dtype='object')

## 6. Conversion des colonnes numériques

Certaines colonnes numériques sont lues comme du texte.

On garde les colonnes géographiques en texte, puis on convertit les autres colonnes en nombres.

In [7]:
colonnes_texte = [
    "zone",
    "r�gion",
    "num�ro",
    "d�partement",
    "cat�gorie_a"
]

for colonne in df.columns:
    if colonne not in colonnes_texte:
        df[colonne] = df[colonne].astype(str)
        df[colonne] = df[colonne].str.replace(" ", "")
        df[colonne] = pd.to_numeric(df[colonne], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 71 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ann�e                                    99 non-null     int64
 1   zone                                     99 non-null     object
 2   r�gion                                   99 non-null     object
 3   num�ro                                   99 non-null     object
 4   d�partement                              99 non-null     object
 5   cat�gorie_a                              97 non-null     object
 6   feux_d'habitations-bureaux               99 non-null     int64
 7   dont_feux_de_chemin�es                   99 non-null     int64
 8   feux_d'erp_avec_local_�_sommeil          99 non-null     int64
 9   feux_d'erp_sans_local_�_sommeil          99 non-null     int64
 10  feux_de_locaux_industriels               99 non-null     int64
 11  feux_de_locaux_artisanaux                99 non-null     int64
 12  feux_de_locaux_agricoles                 99 non-null     int64
 13  feux_sur_voie_publique                   99 non-null     int64
 14  feux_de_v�hicules                        99 non-null     int64
 15  feux_de_v�g�tations                      99 non-null     int64
 16  autres_feux                              99 non-null     int64
 17  incendies                                99 non-null     int64
 18  accidents_sur_lieux_de_travail           99 non-null     int64
 19  accidents_�_domicile                     99 non-null     int64
 20  accidents_de_sport                       99 non-null     int64
 21  accidents_sur_voie_publique              99 non-null     int64
 22  secours_en_montagne                      99 non-null     int64
 23  malaises_sur_lieux_de_travail            99 non-null     int64
 24  malaises_�_domicile_:_urgence_vitale     99 non-null     int64
 25  malaises_�_domicile_:_carence            99 non-null     int64
 26  malaises_en_sport                        99 non-null     int64
 27  malaises_sur_voie_publique               99 non-null     int64
 28  autolyses                                99 non-null     int64
 29  secours_en_piscines_ou_eaux_int�rieures  99 non-null     int64
 30  secours_en_mer_(fdsm)                    99 non-null     int64
 31  intoxications                            99 non-null     int64
 32  dont_intoxications_au_co                 99 non-null     int64
 33  autres_sav                               99 non-null     int64
 34  secours_�_victime                        99 non-null     int64
 35  relevage_de_personnes                    99 non-null     int64
 36  recherche_de_personnes                   99 non-null     int64
 37  aides_�_personne                         99 non-null     int64
 38  secours_�_personne                       99 non-null     int64
 39  accidents_routiers                       99 non-null     int64
 40  accidents_ferroviaires                   99 non-null     int64
 41  accidents_a�riens                        99 non-null     int64
 42  accidents_de_navigation                  99 non-null     int64
 43  accidents_de_t�l�portage                 99 non-null     int64
 44  accidents_de_circulation                 99 non-null     int64
 45  odeurs_-_fuites_de_gaz                   99 non-null     int64
 46  odeurs_(autres_que_gaz)                  99 non-null     int64
 47  fait_dus_�_l'�lectricit�                 99 non-null     int64
 48  pollutions_-_contaminations              99 non-null     int64
 49  autres_risques_technologiques            99 non-null     int64
 50  risques_technologiques                   99 non-null     int64
 51  fuites_d'eau                             99 non-null     int64
 52  inondations                              99 non-null     int64
 53  ouvertures_de_portes                     99 non-null     int64
 54  recherches_d'objets                      99 non-null     int64
 55  bruits_suspects                          99 non-null     int64
 56  protection_des_biens                     99 non-null     int64
 57  fausses_alertes                          99 non-null     int64
 58  dont_fausses_alertes_daaf                99 non-null     int64
 59  faits_d'animaux_(hors_hym�nopt�res)      99 non-null     int64
 60  hym�nopt�res                             99 non-null     int64
 61  d�gagements_de_voies_publiques           99 non-null     int64
 62  nettoyages_de_voies_publiques            99 non-null     int64
 63  �boulements                              99 non-null     int64
 64  d�poses_d'objets                         99 non-null     int64
 65  piquets_de_s�curit�_-_surveillances      99 non-null     int64
 66  engins_explosifs                         99 non-null     int64
 67  autres_op�rations_diverses               99 non-null     int64
 68  divers                                   99 non-null     int64
 69  op�rations_diverses                      99 non-null     int64
 70  total_interventions                      99 non-null     int64
dtypes: int64(66), object(5)
memory usage: 55.0+ KB

Après cette étape, les colonnes de calcul sont bien numériques.

Les données sont maintenant prêtes pour l'analyse.

## 7. Analyse des départements

On cherche les 10 départements avec le plus grand nombre total d'interventions.

In [8]:
top_departements = (
    df[["d�partement", "total_interventions"]]
    .sort_values(by="total_interventions", ascending=False)
    .head(10)
)

top_departements

         d�partement  total_interventions
1              Paris               495397
61              Nord               172471
14  Bouches-du-Rh�ne               151516
64     Pas-de-Calais               142069
35           Gironde               132724
0   Bouches-du-Rh�ne               120317
84               Var               119554
71             Rh�ne               117039
78    Seine-et-Marne               104183
7    Alpes-Maritimes               102620

Cette analyse est utilisée dans le tableau de bord pour afficher le classement des départements.

Elle permet de voir rapidement les territoires avec le plus d'interventions.

## 8. Analyse des grandes catégories

On calcule le total des grandes catégories d'interventions :

- incendies ;
- secours à personne ;
- accidents ;
- opérations diverses.

In [9]:
categories = {
    "Incendies": df["incendies"].sum(),
    "Secours à personne": df["secours_�_personne"].sum(),
    "Accidents": df["accidents_de_circulation"].sum(),
    "Opérations diverses": df["op�rations_diverses"].sum()
}

categories

{'Incendies': np.int64(277138),
 'Secours à personne': np.int64(3778135),
 'Accidents': np.int64(305044),
 'Opérations diverses': np.int64(355036)}

On observe que le secours à personne représente une très grande partie des interventions.

Cette information est importante, car elle montre que les pompiers interviennent majoritairement pour aider les personnes, et pas seulement pour les incendies.

## 9. Part du secours à personne

On calcule la part du secours à personne dans le total des interventions.

In [10]:
total_interventions = df["total_interventions"].sum()
part_secours = categories["Secours à personne"] / total_interventions

part_secours

np.float64(0.7917482992584278)

Cette part est utilisée dans les KPI du tableau de bord Excel.

## 10. Choix pour le tableau de bord

Après l'exploration, j'ai choisi de créer un tableau de bord Excel avec :

- un filtre par région ;
- un filtre par catégorie ;
- un top 10 des départements ;
- des indicateurs clés ;
- un graphique de classement ;
- un graphique de répartition des catégories.

L'objectif est d'avoir un reporting simple à lire et facile à mettre à jour.

## 11. Utilisation des fichiers Python du projet

Le notebook sert à montrer le raisonnement.

Le code final du projet est rangé dans le dossier `src`.

On peut utiliser ces fichiers pour générer automatiquement le fichier Excel final.

In [11]:
import sys
sys.path.append("../src")

from chargement import charger_donnees
from nettoyage import nettoyer_noms_colonnes, convertir_colonnes_numeriques
from analyse import top_10_departements, grandes_categories
from export_excel import exporter_excel

In [12]:
df_final = charger_donnees("../data/interventions2023.csv")
df_final = nettoyer_noms_colonnes(df_final)
df_final = convertir_colonnes_numeriques(df_final)

top_departements_final = top_10_departements(df_final)
categories_final = grandes_categories(df_final)

top_departements_final

         d�partement  total_interventions
1              Paris               495397
61              Nord               172471
14  Bouches-du-Rh�ne               151516
64     Pas-de-Calais               142069
35           Gironde               132724
0   Bouches-du-Rh�ne               120317
84               Var               119554
71             Rh�ne               117039
78    Seine-et-Marne               104183
7    Alpes-Maritimes               102620

Le fichier Excel final est généré par le script principal `src/main.py`.

Je ne le génère pas directement ici pour éviter de mélanger le notebook et le script final.

La commande utilisée dans le terminal est :

```bash
python src/main.py
```

## 12. Conclusion

Cette exploration a permis de comprendre le jeu de données et de préparer les analyses utilisées dans le tableau de bord.

Les principales étapes ont été :

- charger les données ;
- observer la structure du fichier ;
- nettoyer les noms de colonnes ;
- convertir les colonnes numériques ;
- analyser les départements ;
- analyser les grandes catégories d'interventions ;
- construire un tableau de bord Excel dynamique.

Le projet final permet de générer automatiquement un fichier Excel à partir du fichier CSV.